name: Test Dormant Users Action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run action locally
        uses: ./
        with:
          github_token: ${{ secrets.ORG_AUDIT_TOKEN }}
          org_names: yubi-migration-test
          days_inactive_threshold: 30


      - name: Upload dormant users report
        uses: actions/upload-artifact@v4
        with:
          name: dormant-users-report
          path: "*.csv"

